command:
  - python
  - dash_app.py

env:
  - name: PGHOST
    value: "instance-6b59171b-cee8-4acc-9209-6c848ffbfbfe.database.cloud.databricks.com"
  - name: PGDATABASE
    value: "databricks_postgres"
  - name: PGUSER
    value: "f6e5df56-fa6c-4262-970b-8f27dd6fa850"
  - name: PGPORT
    value: "5432"
  - name: PGSSLMODE
    value: "require"
  - name: PGAPPNAME
    value: "lakebase-training-app"
