command:
  - python
  - dash_app.py

env:
  - name: PGHOST
    value: "instance-6b59171b-cee8-4acc-9209-6c848ffbfbfe.database.cloud.databricks.com"
  - name: PGDATABASE
    value: "databricks_postgres"
  - name: PGUSER
    value: "1e6260c5-f44b-4d66-bb19-ccd360f98b36"
  - name: PGPORT
    value: "5432"
  - name: PGSSLMODE
    value: "require"
  - name: PGAPPNAME
    value: "lakebase-training-app"
