command:
  - python
  - dash_app.py

env:
  # Sensitive values - retrieved from Databricks Secrets
  - name: PGHOST
    valueFrom:
      secretRef:
        name: lakebase-db-host
        key: host
  - name: PGUSER
    valueFrom:
      secretRef:
        name: lakebase-db-user
        key: user
  # Non-sensitive configuration values
  - name: PGDATABASE
    value: "databricks_postgres"
  - name: PGPORT
    value: "5432"
  - name: PGSSLMODE
    value: "require"
  - name: PGAPPNAME
    value: "lakebase-training-app"
